# Site settings
name: Aditya Ramesh
title: Aditya Ramesh | Electronics Engineer
description: A detail oriented electronics engineering student intersted in DSP.
url: https://theadityaramesh.github.io/
baseurl: ''
email: mail.aditya.ramesh@gmail.com
cover: https://theadityaramesh.github.io/img/og.png
logo: https://theadityaramesh.github.io/img/emojis/technologist.png
resume: https://theadityaramesh.github.io/resume.pdf
social:
  - title: email
    url: mailto:mail.aditya.ramesh@gmail.com
  - title: blog
    url: https://theadityaramesh.github.io/adityarameshblog
  - title: instagram
    url: https://instagram.com/theadityaramesh
  - title: github
    url: https://github.com/theAdityaRamesh
  - title: linkedin
    url: https://www.linkedin.com/in/theadityaramesh

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
